## Level 10 Numpy

---

### numpy basic --->

In [3]:
import numpy as np

In [4]:
a_np = np.array([1, 2, 3, 4, 5])
type(a_np)

numpy.ndarray

In [5]:
a_np[2:4]

array([3, 4])

In [6]:
a_np + 1

array([2, 3, 4, 5, 6])

In [7]:
a_np * 2

array([ 2,  4,  6,  8, 10])

In [8]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [4, 9, 12]
])

In [9]:
array_2d + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 5, 10, 13]])

In [10]:
array_2d[1] + 1

array([5, 6, 7])

In [11]:
print(len(array_2d))
print(array_2d.shape)
print(array_2d.size)

3
(3, 3)
9


In [12]:
print(a_np.ndim)
print(array_2d.ndim)

1
2


In [13]:
array_2d.dtype

dtype('int32')

In [14]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, "6"],
    [7, 8, 9]], dtype=np.float32)
array_2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [15]:
np.full((5, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [16]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.zeros((3, 2)) + 10

array([[10., 10.],
       [10., 10.],
       [10., 10.]])

In [18]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [19]:
line = np.linspace(1, 100, 5)
print(line)

[  1.    25.75  50.5   75.25 100.  ]


In [20]:
np.sqrt(array_2d)

array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898],
       [2.6457512, 2.828427 , 3.       ]], dtype=float32)

In [21]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
numbers[2::2]

array([3, 5, 7, 9])

In [22]:
avg = np.mean(numbers)
print(avg)
print(numbers > avg)
print(numbers[numbers > avg])

5.5
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


---
### vectorization --->

In [23]:
def calc(val):
    if val > 10:
        return val * 10
    else: return val * 5

In [24]:
mul = np.vectorize(calc)

In [25]:
arr = np.array([1, 2, 3, 11, 5])

In [26]:
mul(arr)

array([  5,  10,  15, 110,  25])

---
### condition --->

In [27]:
arr = np.array([1, 2, 100, 98, 45, 90, 15])


In [28]:
arr[(arr > 50) & (arr < 100)]

array([98, 90])

In [29]:
np.where(arr < 50, "yes", np.where(arr > 90, "yes", "no"))

array(['yes', 'yes', 'yes', 'yes', 'yes', 'no', 'yes'], dtype='<U3')

---
### flattening, resizing arrays --->

In [30]:
scores = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]])

np.resize(scores, (6, 2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [31]:
scores.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

---
### transposing --->

In [32]:
scores.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

---
### concatening --->

In [33]:
data1 = np.array([12, 13])
data2 = np.array([15, 17])

np.concatenate((data1, data2))

array([12, 13, 15, 17])

In [34]:
np.hstack((data1, data2))

array([12, 13, 15, 17])

In [35]:
np.vstack((data1, data2))

array([[12, 13],
       [15, 17]])

---
### handling missing data --->

In [36]:
import numpy as np
customer_data = np.array([100, 150, np.nan, 200, 300, 175])

In [37]:
missing_values = np.isnan(customer_data)

In [38]:
print(np.sum(missing_values))

1


In [39]:
zero_filled = np.nan_to_num(customer_data)
zero_filled

array([100., 150.,   0., 200., 300., 175.])

In [40]:
mean_data = np.nanmean(customer_data)
mean_data

185.0

In [41]:
data_mean_filled = np.where(np.isnan(customer_data), mean_data, customer_data)
data_mean_filled

array([100., 150., 185., 200., 300., 175.])

In [42]:
data_without_nan = customer_data[~np.isnan(customer_data)]
data_without_nan

array([100., 150., 200., 300., 175.])

#### forward and backward filling of missing data

In [43]:
copy_of_cd = np.copy(customer_data)
mask = np.isnan(copy_of_cd)

copy_of_cd[mask] = np.roll(copy_of_cd, shift=-1)[mask]
print(copy_of_cd)

copy_of_cd_f = np.copy(customer_data)
mask = np.isnan(copy_of_cd_f)
copy_of_cd_f[mask] = np.roll(copy_of_cd_f, shift=1)[mask]
print(copy_of_cd_f)

[100. 150. 200. 200. 300. 175.]
[100. 150. 150. 200. 300. 175.]


---
### files --->

In [44]:
age = np.array([1, 23, 6, 45, 90, 48])

In [45]:
np.save("age.npy", age)

In [46]:
loaded_age = np.load("age.npy")
print(loaded_age)

[ 1 23  6 45 90 48]


In [47]:
np.savetxt("age.txt", loaded_age, delimiter=",")

In [48]:
new_age = np.loadtxt("age.txt", delimiter=",")
print(new_age)

[ 1. 23.  6. 45. 90. 48.]


---