## Level 10 Numpy

---

### numpy basic --->

In [25]:
import numpy as np

In [26]:
a_np = np.array([1, 2, 3, 4, 5])
type(a_np)

numpy.ndarray

In [27]:
a_np[2:4]

array([3, 4])

In [28]:
a_np + 1

array([2, 3, 4, 5, 6])

In [29]:
a_np * 2

array([ 2,  4,  6,  8, 10])

In [30]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [4, 9, 12]
])

In [31]:
array_2d + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 5, 10, 13]])

In [32]:
array_2d[1] + 1

array([5, 6, 7])

In [35]:
print(len(array_2d))
print(array_2d.shape)
print(array_2d.size)

3
(3, 3)
9


In [37]:
print(a_np.ndim)
print(array_2d.ndim)

1
2


In [38]:
array_2d.dtype

dtype('int32')

In [41]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, "6"],
    [7, 8, 9]], dtype=np.float32)
array_2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [42]:
np.full((5, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [44]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.zeros((3, 2)) + 10

array([[10., 10.],
       [10., 10.],
       [10., 10.]])

In [49]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [51]:
line = np.linspace(1, 100, 5)
print(line)

[  1.    25.75  50.5   75.25 100.  ]


In [52]:
np.sqrt(array_2d)

array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898],
       [2.6457512, 2.828427 , 3.       ]], dtype=float32)

In [53]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
numbers[2::2]

array([3, 5, 7, 9])

In [55]:
avg = np.mean(numbers)
print(avg)
print(numbers > avg)
print(numbers[numbers > avg])

5.5
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


---
### vectorization --->

In [56]:
def calc(val):
    if val > 10:
        return val * 10
    else: return val * 5

In [57]:
mul = np.vectorize(calc)

In [61]:
arr = np.array([1, 2, 3, 11, 5])

In [62]:
mul(arr)

array([  5,  10,  15, 110,  25])

---
### condition --->

In [63]:
arr = np.array([1, 2, 100, 98, 45, 90, 15])


In [64]:
arr[(arr > 50) & (arr < 100)]

array([98, 90])

In [66]:
np.where(arr < 50, "yes", np.where(arr > 90, "yes", "no"))

array(['yes', 'yes', 'yes', 'yes', 'yes', 'no', 'yes'], dtype='<U3')

---
### flattening, resizing arrays --->

In [68]:
scores = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]])

np.resize(scores, (6, 2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [70]:
scores.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

---
### transposing --->

In [71]:
scores.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

---
### concatening --->

In [74]:
data1 = np.array([12, 13])
data2 = np.array([15, 17])

np.concatenate((data1, data2))

array([12, 13, 15, 17])

In [75]:
np.hstack((data1, data2))

array([12, 13, 15, 17])

In [76]:
np.vstack((data1, data2))

array([[12, 13],
       [15, 17]])